export class Movie {
	id: number;
	name: string;
	releaseYear: number;

}
/** OUR MOVIE MODEL WILL ENSURE THAT ANYTIME WE CREATE A MODEL INSTANCE WE ARE NOT PASSING IN ERONOUS PARAMETER  
WE CAN THEREFORE USE THIS IN OUR COMPONENT BY IMPORTING IT, AND ALSO ASSIGNING AN OBJECT TO IT*/
